Wingman/urls.py
from django.contrib import admin
from django.urls import path, include
from main_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls'))
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('mecze/', views.AllMatchesView.as_view(), name="all_matches"),
    path('pools/', views.AllPoolsView.as_view(), name="pool_rank"),
    path('podsumowanie/', views.SummaryView.as_view(), name="summary"),
    path('podsumowanie20/', views.Summary20View.as_view(), name="summary20"),
    path('new_matches/', views.new_matches_file_view, name="new_matches"),
    path('new_matches2/', views.new_matches_table_view, name="new_matches2")
]

main_app/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField
from datetime import datetime

# Create your models here.
class Pools(models.Model):
    pool_num = models.IntegerField(default=0)
    pool_m_won = models.IntegerField(default=0)
    pool_m_lost = models.IntegerField(default=0)
    pool_m_tied = models.IntegerField(default=0)
    pool_r_won = models.IntegerField(default=0)
    pool_r_lost = models.IntegerField(default=0)
    pool_r_rate = models.FloatField(default=0.0)
    pool_K1 = models.IntegerField(default=0)
    pool_A1 = models.IntegerField(default=0)
    pool_D1 = models.IntegerField(default=0)
    pool_KD1 = models.FloatField(default=0.0)
    pool_MVP1 = models.IntegerField(default=0)
    pool_HSP1 = models.IntegerField(default=0)
    pool_pts1 = models.IntegerField(default=0)
    pool_ptsadd1 = models.IntegerField(default=0)
    pool_K2 = models.IntegerField(default=0)
    pool_A2 = models.IntegerField(default=0)
    pool_D2 = models.IntegerField(default=0)
    pool_KD2 = models.FloatField(default=0.0)
    pool_MVP2 = models.IntegerField(default=0)
    pool_HSP2 = models.IntegerField(default=0)
    pool_pts2 = models.IntegerField(default=0)
    pool_ptsadd2 = models.IntegerField(default=0)
    pool_skipped = ArrayField(models.CharField(max_length=32, blank=True), default=list)

    def __str__(self):
        return 'Pool nr ' + str(self.pool_num)


class Matches(models.Model):
    match_map = models.CharField(max_length=32)
    match_date = models.DateTimeField(unique=True)
    match_duration = models.DurationField()
    match_waiting = models.DurationField()
    match_r_won = models.IntegerField()
    match_r_lost = models.IntegerField()
    match_K1 = models.IntegerField()
    match_A1 = models.IntegerField()
    match_D1 = models.IntegerField()
    match_MVP1 = models.IntegerField()
    match_HSP1 = models.IntegerField()
    match_score1 = models.IntegerField()
    match_K2 = models.IntegerField()
    match_A2 = models.IntegerField()
    match_D2 = models.IntegerField()
    match_MVP2 = models.IntegerField()
    match_HSP2 = models.IntegerField()
    match_score2 = models.IntegerField()
    match_pool = models.ForeignKey(Pools, on_delete=models.CASCADE)

    def __str__(self):
        return self.match_date.strftime('%Y-%m-%d') + ' ' + self.match_map

main_app/forms.py
from django import forms
from django.core.validators import FileExtensionValidator

class HtmlFileForm(forms.Form):
    file = forms.FileField(required=False,
                           label="Html file:",
                           validators=[FileExtensionValidator(allowed_extensions=['html'])]
                           )

main_app/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView
from django.shortcuts import redirect
from django.urls import reverse
from .models import Matches, Pools
from .forms import HtmlFileForm
from main_app.utils.statistica import stat, stat20
from main_app.utils.new_matches_scrap import scrap_matches, prep_list, update_models


# Create your views here.
class IndexView(TemplateView):
    template_name = 'main_app/index.html'


class AllMatchesView(ListView):
    template_name = 'main_app/matches.html'
    queryset = Matches.objects.order_by('-match_date')


class AllPoolsView(ListView):
    template_name = 'main_app/pools.html'
    queryset = Pools.objects.order_by('-pool_r_rate')

    def get_context_data(self,**kwargs):
        context  = super().get_context_data(**kwargs)
        context['max_pool'] = len(Pools.objects.all())
        return context


class NewMatchesView(TemplateView):
    template_name = 'main_app/new_matches_form.html'


class SummaryView(TemplateView):
    template_name = 'main_app/summary.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        try:
            all_s, indiv_s = stat()
        except:
            all_s, indiv_s = 0, 0

        context['all_stats_tab'] = all_s
        context['indiv_stats_tab'] = indiv_s
        context['stats20'] = False
        return context


class Summary20View(TemplateView):
    template_name = 'main_app/summary.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        try:
            all_s, indiv_s = stat20()
        except:
            all_s, indiv_s = 0, 0

        context['all_stats_tab'] = all_s
        context['indiv_stats_tab'] = indiv_s
        context['stats20'] = True
        return context


def new_matches_table_view(request):
    matches_to_do = prep_list()
    if request.method == "POST":
        update_models(request, matches_to_do)
        return redirect(reverse('all_matches'))

    return render(request, 'main_app/new_matches_choice.html', {'matches': matches_to_do})


def new_matches_file_view(request):
    form = HtmlFileForm()

    if request.method == "POST":
        form = HtmlFileForm(request.POST)

        if form.is_valid():
            valid_matches = scrap_matches(request.FILES['file'])
            return redirect(reverse('new_matches2'))

    return render(request, 'main_app/new_matches_form.html', {'form': form})

templates/main_app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Wingman</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "main_app/main.css" %}"/>

    <link rel="shortcut icon" href="{% static 'counterstrike.ico' %}"/>

  </head>
  <body>

      <nav class="navbar fixed-top navbar-dark bg-dark navbar-expand-lg">
        <a class="navbar-brand" href="{% url "index" %}">Wingman</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'summary' %}">Summary</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'summary20' %}">Summary 20</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'pool_rank' %}">Pool ranking</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'all_matches' %}">Match list</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'new_matches' %}">New matches</a>
            </li>
          </ul>
        </div>

      </nav>


      <div id="everything">
        {% block after_nav %}

        {% endblock %}
      </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

  </body>
</html>

templates/main_app/index.html
<!DOCTYPE html>
{% extends "main_app/base.html" %}
  {% block after_nav %}

    <div id="index" class="container">
      <h1>Welcome to Wingman project</h1>

      <br>
      <h3>How it works:</h3>
      <ol>
        <li class="lead">Match results along with statistics can be found on the official Steam website, but they are only available after logging in, which makes it impossible to scrape data directly from there.</li>
        <li class="lead">After a game session, I save the web page as an .html file and upload it to the form available at "New matches".</li>
        <li class="lead">The script, using BeautifulSoup, scrapes data on new matches and saves it in a temporary .txt file based on which a new form is created where I can select matches that were played outside of pools and should not be included in the database.</li>
        <li class="lead">After verification the matches are added either to the list of matches outside of pools or to the database.</li>
        <li class="lead">When entering the summary or summary 20 page, another script creates a summary using data aggregation.</li>
        <li class="lead">The list of matches and the ranking of pools is displayed using ListView.</li>
        <li class="lead">The project is hosted on Heroku and therefore the database used is PostgreSQL.</li>
      </ol>


      <br>
      <h3>Rules of play:</h3>
      <ol>
        <li class="lead">Out of all the maps available in the Wingman CS:GO queue, we play 7 different ones. We call such a set of 7 matches a 'pool'.</li>
        <li class="lead">After each pool, maps with the worst round ratio are chosen to be skipped in the next pool so that each pool has 7 maps. The only exception is when we lose a match 0:9, in which case this map will be skipped in the next pool regardless of the round ratio.</li>
        <li class="lead">You cannot skip maps that were skipped in the previous pool.</li>
        <li class="lead">Two maps, currently: Calavera, Pitstop, were recently added to the game and we decided that in each pool we will play one of them, skip the other and complete the pool with 6 maps from the others. The matchmaking for CS:GO randomly decides which of these two maps will appear in the pool.</li>
      </ol>

    </div>

  {% endblock %}

templates/main_app/matches.html
{% extends "main_app/base.html" %}
{% load my_filter %}
  {% block after_nav %}

    <style>
      table tr:nth-of-type(7n+{{ matches_list.count|modulo:7 }}) td {
          border-bottom: 2px solid black;
      }
    </style>

    <div class="container">
      <h1>All matches</h1>
      <table>
        <thead class="end-row">
          <th>Map</th>
          <th>Date</th>
          <th>Waiting</th>
          <th>Duration</th>
          <th class='end-col'>Result</th>
          <th class="greenback">K</th>
          <th class="yellowback">A</th>
          <th class="redback">D</th>
          <th class="blueback">MVP</th>
          <th class="blueback">HSP</th>
          <th class='end-col blueback'>Pts</th>
          <th class="greenback">K</th>
          <th class="yellowback">A</th>
          <th class="redback">D</th>
          <th class="blueback">MVP</th>
          <th class="blueback">HSP</th>
          <th class="blueback">Pts</th>
        </thead>

        {% for m in matches_list %}
          <tr>
            <td>{{m.match_map}}</td>
            <td>{{m.match_date | date:'Y-m-d H:i'}}</td>
            <td>{{m.match_waiting | disp_timedelta}}</td>
            <td>{{m.match_duration | disp_timedelta}}</td>

            {% if m.match_r_won == 9 %}
              <td class='end-col mwon'><strong>{{m.match_r_won}}:{{m.match_r_lost}}</strong></td>
            {% elif m.match_r_won == 8 %}
              <td class='end-col mtied'><strong>{{m.match_r_won}}:{{m.match_r_lost}}</strong></td>
            {% else %}
              <td class='end-col mlost'><strong>{{m.match_r_won}}:{{m.match_r_lost}}</strong></td>
            {% endif %}

            <td class='num greenback'>{{m.match_K1}}</td>
            <td class='num yellowback'>{{m.match_A1}}</td>
            <td class='num redback'>{{m.match_D1}}</td>
            <td class='num blueback'>{{m.match_MVP1}}</td>
            <td class='num blueback'>{{m.match_HSP1}}</td>
            <td class='num end-col blueback'>{{m.match_score1}}</td>
            <td class='num greenback'>{{m.match_K2}}</td>
            <td class='num yellowback'>{{m.match_A2}}</td>
            <td class='num redback'>{{m.match_D2}}</td>
            <td class='num blueback'>{{m.match_MVP2}}</td>
            <td class='num blueback'>{{m.match_HSP2}}</td>
            <td class='num blueback'>{{m.match_score2}}</td>
          </tr>
        {% endfor %}

      </table>
    </div>

  {% endblock %}

templates/main_app/new_matches_choice.html
{% extends "main_app/base.html" %}
{% load my_filter %}
  {% block after_nav %}

    <div class="container">

      <h3>Check matches that were played outside pools:</h3>

      <form method="post">
        {% csrf_token %}
        {% for m in matches %}

          <input type="checkbox" name="{{ m.0.1 }}">
          <span>{{ m.0.1|rawdate }} {{ m.0.0 }} {{ m.1.12 }}:{{ m.1.13 }}</span>
          <br>

        {% endfor %}

        <input type="submit" name="" value="Submit">

      </form>


    </div>

  {% endblock %}

templates/main_app/new_matches_form.html
{% extends "main_app/base.html" %}
  {% block after_nav %}

    <div class="container">

      <h3>To add new matches upload html file here:</h3>

      <form method="POST" enctype="multipart/form-data">

        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">

      </form>


    </div>

  {% endblock %}

templates/main_app/pools.html
<!DOCTYPE html>
{% extends "main_app/base.html" %}
  {% block after_nav %}

    <div class="container">
      <h1>Pool ranking</h1>

      <table>

          <thead class="end-row">
            <th>Rank</th>
            <th class="end-col">Num</th>
            <th class="greenback">MW</th>
            <th class="redback">ML</th>
            <th class="end-col yellowback">MT</th>
            <th class="greenback">RW</th>
            <th class="redback">RL</th>
            <th class="end-col yellowback">RR</th>
            <th class="greenback">K</th>
            <th class="yellowback">A</th>
            <th class="redback">D</th>
            <th class="yellowback">KD</th>
            <th class="blueback">MVP</th>
            <th class="blueback">HSP</th>
            <th class="blueback">Pts</th>
            <th class="end-col blueback">Pts+</th>
            <th class="greenback">K</th>
            <th class="yellowback">A</th>
            <th class="redback">D</th>
            <th class="yellowback">KD</th>
            <th class="blueback">MVP</th>
            <th class="blueback">HSP</th>
            <th class="blueback">Pts</th>
            <th class="end-col blueback">Pts+</th>
          </thead>

        {% for p in pools_list %}
          {% if p.pool_num == max_pool %}
            <tr class="highl">
          {% else %}
            <tr>
          {% endif %}
            <td class="numf">{{ forloop.counter }}</td>
            <td class="end-col numf">{{ p.pool_num }}</td>
            <td class="num greenback">{{ p.pool_m_won }}</td>
            <td class="num redback">{{ p.pool_m_lost }}</td>
            <td class="end-col num yellowback">{{ p.pool_m_tied }}</td>
            <td class="num greenback">{{ p.pool_r_won }}</td>
            <td class="num redback">{{ p.pool_r_lost }}</td>
            <td class="end-col numf yellowback">{{ p.pool_r_rate|floatformat:3 }}</td>
            <td class="num greenback">{{ p.pool_K1 }}</td>
            <td class="num yellowback">{{ p.pool_A1 }}</td>
            <td class="num redback">{{ p.pool_D1 }}</td>
            <td class="numf yellowback">{{ p.pool_KD1|floatformat:3 }}</td>
            <td class="num blueback">{{ p.pool_MVP1 }}</td>
            <td class="num blueback">{{ p.pool_HSP1 }}</td>
            <td class="num blueback">{{ p.pool_pts1 }}</td>
            <td class="end-col num blueback">{{ p.pool_ptsadd1 }}</td>
            <td class="num greenback">{{ p.pool_K2 }}</td>
            <td class="num yellowback">{{ p.pool_A2 }}</td>
            <td class="num redback">{{ p.pool_D2 }}</td>
            <td class="numf yellowback">{{ p.pool_KD2|floatformat:3 }}</td>
            <td class="num blueback">{{ p.pool_MVP2 }}</td>
            <td class="num blueback">{{ p.pool_HSP2 }}</td>
            <td class="num blueback">{{ p.pool_pts2 }}</td>
            <td class="end-col num blueback">{{ p.pool_ptsadd2 }}</td>
          </tr>

        {% endfor %}

      </table>
    </div>

  {% endblock %}

templates/main_app/summary.html
<!DOCTYPE html>
{% extends "main_app/base.html" %}
{% load my_filter %}
  {% block after_nav %}

    <div class="container">
      <h2>Match summary</h2>

      <table>

        <thead class="end-row">
          <th>Map</th>
          <th class="greenback">MW</th>
          <th class="redback">ML</th>
          <th class="yellowback">MT</th>
          <th class="yellowback">WR</th>
          <th class="blueback">Wait</th>
          <th class="blueback">Dur</th>
          <th class="redback">Skip</th>
          <th class="greenback">RW</th>
          <th class="redback">RL</th>
          <th class="yellowback">Rds</th>
          <th class="yellowback">RR</th>
          {% if stats20 %}
            <th class="numpods blueback">U/D</th>
            <th class="numpods blueback">OUT</th>
            <th class="numfpods yellowback">Proj. RR</th>
          {% endif %}
        </thead>

        {% for map in all_stats_tab %}
          {% if map.map_name == "*" %}
            <tr class="highl">
              <td>All</td>
          {% else %}
            <tr>
              <td class="{{map.status}}">{{map.map_name}}</td>
          {% endif %}
              <td class="numf greenback">{{map.m_won}}</td>
              <td class="numf redback">{{map.m_lost}}</td>
              <td class="numf yellowback">{{map.m_tied}}</td>
              <td class="numpods yellowback">{{map.m_win_rate | floatformat:3}}</td>
              <td class="numpods blueback">{{map.m_waiting | disp_timedelta}}</td>
              <td class="numpods blueback">{{map.m_duration | disp_timedelta}}</td>
              <td class="numpods redback">{{map.m_skips}}</td>
              <td class="numpods greenback">{{map.r_won}}</td>
              <td class="numpods redback">{{map.r_lost}}</td>
              <td class="numpods yellowback">{{map.r_mean | floatformat:2}}</td>
              <td class="numpods yellowback">{{map.r_rate | floatformat:3}}</td>
              {% if stats20 %}
                <td class="numpods blueback">{{map.ud}}</td>
                <td class="numpods blueback">{{map.m_out | m_result}}</td>
                <td class="yellowback">{{map.proj_RR | projrr}}</td>
              {% endif %}
            </tr>
        {% endfor %}

      </table>

      <p class="legend">
        <strong>Background color</strong> - result of match in current pool (green - won, yellow - tied, red - lost, blue - skipped), grey if map cannot be played anymore, none if map yet to play,
        <strong><s>Map</s></strong> - projected skip in next pool,
        <strong>MW</strong> - matches won,
        <strong>ML</strong> - matches lost,
        <strong>MT</strong> - matches tied,
        <strong>WR</strong> - win ratio (MW/ML),
        <strong>Wait</strong> - mean waiting time for a match,
        <strong>Dur</strong> - mean total time of a match,
        <strong>Skip</strong> - number of map skips,
        <strong>RW</strong> - round won,
        <strong>RL</strong> - round lost,
        <strong>Rds</strong> - mean number of rounds in single match,
        <strong>RR</strong> - round ratio (RW/RL){% if stats20 %},
          <strong>U/D</strong> - match result that guarantee map to be skipped or be save from skip,
          <strong>OUT</strong> - match result that will not be counted next pool (matches in 20th pool from now),
          <strong>Proj. RR</strong> - projected round rate - if played - round rate after OUT, else round rate with result 9:0 or 0:9
        {% endif %}
      </p>

      <p></p>
      <h2>Individual summary</h2>

      <table>

        <thead class="end-row">
          <th>Map</th>
          <th class="greenback">K</th>
          <th class="yellowback">A</th>
          <th class="redback">D</th>
          <th class="blueback">MVP</th>
          <th class="blueback">HSP</th>
          <th class="blueback">Pts</th>
          <th class="blueback">Pts+</th>
          <th class="yellowback">KR</th>
          <th class="yellowback end-col">KD</th>
          <th class="greenback">K</th>
          <th class="yellowback">A</th>
          <th class="redback">D</th>
          <th class="blueback">MVP</th>
          <th class="blueback">HSP</th>
          <th class="blueback">Pts</th>
          <th class="blueback">Pts+</th>
          <th class="yellowback">KR</th>
          <th class="yellowback end-col">KD</th>
          <th class="yellowback">Total KD</th>
        </thead>

        {% for map in indiv_stats_tab %}
          {% if map.map_name == "*" %}
            <tr class="highl">
              <td>All</td>
          {% else %}
            <tr>
              <td>{{map.map_name}}</td>
          {% endif %}
              <td class="numf greenback">{{map.m_K1}}</td>
              <td class="numf yellowback">{{map.m_A1}}</td>
              <td class="numf redback">{{map.m_D1}}</td>
              <td class="numf blueback">{{map.m_MVP1}}</td>
              <td class="numf blueback">{{map.m_HSP1 | floatformat:1}}</td>
              <td class="numf blueback">{{map.m_pts1}}</td>
              <td class="numf blueback">{{map.m_addpts1}}</td>
              <td class="numf yellowback">{{map.m_KR1 | floatformat:3}}</td>
              <td class="numf yellowback end-col">{{map.m_KD1 | floatformat:3}}</td>
              <td class="numf greenback">{{map.m_K2}}</td>
              <td class="numf yellowback">{{map.m_A2}}</td>
              <td class="numf redback">{{map.m_D2}}</td>
              <td class="numf blueback">{{map.m_MVP2}}</td>
              <td class="numf blueback">{{map.m_HSP2 | floatformat:1}}</td>
              <td class="numf blueback">{{map.m_pts2}}</td>
              <td class="numf blueback">{{map.m_addpts2}}</td>
              <td class="numf yellowback">{{map.m_KR2 | floatformat:3}}</td>
              <td class="numf yellowback end-col">{{map.m_KD2 | floatformat:3}}</td>
              <td class="numf yellowback">{{map.tot_KD | floatformat:3}}</td>
            </tr>
        {% endfor %}

      </table>

      <p class="legend">
        <strong>K</strong> - kills,
        <strong>A</strong> - assists,
        <strong>D</strong> - deaths,
        <strong>MVP</strong> - number of MVPs,
        <strong>HSP</strong> - headshot percentage,
        <strong>Pts</strong> - points in table,
        <strong>Pts+</strong> - points that are not from kills and assists (eg. planting bomb),
        <strong>KR</strong> - kills per round (K/(RW+RL)),
        <strong>KD</strong> - kill-death ratio (K/D),
        <strong>Total KD</strong> - kill-death ratio if we were one player ((K1+K2)/(D1+D2))
      </p>


    </div>

  {% endblock %}